# Documentation:
# - alacritty(5)
# - https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd

[font]
# * https://wiki.archlinux.org/index.php/font_configuration#Fontconfig_configuration
# * file:///usr/share/doc/fontconfig/fontconfig-user.html
size = 8
normal = { family = "Terminus" }

[mouse]
hide_when_typing = true

[window]
padding = { x = 2, y = 2 }

[general]
import = [
    "~/.config/alacritty/colors.toml",
    "~/.config/alacritty/keybindings.toml",
]
